---
# Input

# Packet discarding
# Discards packets depending on their type.
:discard_non_ip_packets: false
:discard_tcp_ip_packets: false
:discard_udp_ip_packets: false
:discard_other_ip_packets: false

# Data Read
:read_time: true
:read_size: true


# Output format, possibles:
# json (default)
# yaml
# xml
:default_output: json

# Sort? (default: true)
:sort: true

# Sorts packets by this packet value, possibles:
# data_time (default)
# data_size
:sort_by: data_time

# Sorts ascending (default: true)
:sort_asc: true

# Adds XML Declaration to XML output (default: false)
:xml_declaration: false

# JSON & YAML: variable name
# XML: parent tag
:data_main: data

# XML: Tag for each packet
:data_packet: packet

# JSON & YAML: hash key for Timestamp
# XML: attribute for Timestamp
:data_time: ts

# JSON & YAML: hash key for Size
# XML: attribute for size
:data_size: sz
