---
# Input
# Discards non IP packet values (default: false)
#:discard_non_ip: false

# Discards IP (TCP & UDP also) packet values (default: false)
#:discard_ip: false

# Discards TCP packet values (default: false)
#:discard_tcp: false

# Discards UDP packet values (default: false)
#:discard_udp: false

# Data Read
:read_time: true
:read_size: true


# Output format, possibles:
# :json (default)
# :yaml
# :xml
# (colon at the beginning is mandatory)
:default_output: :json

# Sort? (default: true)
:sort: true

# Sorts packets by this packet value, possibles:
# :tag_time (default)
# :tag_size
:sort_by: :tag_time

# Sorts ascending (default: true)
:sort_asc: false

# Adds XML Declaration to XML output (default: false)
:xml_declaration: false

# JSON: variable name
# XML: parent tag
:tag_main: data

# XML: Tag for each packet
:tag_packet: packet

# JSON: hash key for Timestamp
# XML: attribute for Timestamp
:tag_time: ts

# JSON: hash key for Size
# XML: attribute for size
:tag_size: sz
